import { motion } from 'motion/react'
import { FadingVideo } from '../ui/FadingVideo'
import { GrainOverlay } from '../ui/GrainOverlay'
import { navigate } from '../../lib/navigation'

/** Render the cinematic entry point for the Tessera product. */
export function Hero(): JSX.Element {
  return <section className="relative flex min-h-[100dvh] items-end overflow-hidden"><FadingVideo /><div className="absolute inset-0 z-[2] bg-[linear-gradient(to_top,var(--bg-primary)_0%,rgba(10,10,15,0.55)_35%,transparent_65%)]" /><GrainOverlay /><div className="relative z-10 flex w-full items-end"><div className="flex max-w-2xl flex-col items-start px-6 pb-24 md:px-10 md:pb-28"><motion.span className="font-mono text-xs uppercase tracking-[0.15em] text-[var(--accent)]" initial={{ opacity: 0, filter: 'blur(8px)', y: 20 }} animate={{ opacity: 1, filter: 'blur(0px)', y: 0 }} transition={{ duration: 0.6, delay: 0.2 }}>private credit on starknet</motion.span><motion.h1 className="mt-5 font-serif text-[clamp(2.75rem,6vw,5.5rem)] leading-[1.02] text-[var(--text-primary)]" initial={{ opacity: 0, filter: 'blur(8px)', y: 20 }} animate={{ opacity: 1, filter: 'blur(0px)', y: 0 }} transition={{ duration: 0.6, delay: 0.35 }}>Borrow privately.<br />Prove you repay.</motion.h1><motion.p className="mt-6 max-w-md text-lg font-light leading-[1.6] text-[var(--text-secondary)]" initial={{ opacity: 0, filter: 'blur(8px)', y: 20 }} animate={{ opacity: 1, filter: 'blur(0px)', y: 0 }} transition={{ duration: 0.6, delay: 0.5 }}>Lend and borrow through the STRK20 pool, then prove your repayment history without revealing a single amount, counterparty or wallet.</motion.p><motion.div className="mt-8 flex items-center gap-6" initial={{ opacity: 0, filter: 'blur(8px)', y: 20 }} animate={{ opacity: 1, filter: 'blur(0px)', y: 0 }} transition={{ duration: 0.6, delay: 0.65 }}><button className="liquid-glass-strong rounded-full px-6 py-3 text-sm font-medium text-[var(--text-primary)] transition-transform hover:scale-[1.02] active:scale-[0.98]" onClick={() => navigate('/app')}>Open the app</button><a className="text-sm font-medium text-[var(--text-secondary)] transition-colors hover:text-[var(--text-primary)]" href="#proof">See the proof</a></motion.div></div></div></section>
}
