import { ArrowUpRight } from 'lucide-react'
import { FadeIn } from '../ui/FadeIn'

/** Render the bento ledger explaining notes, nullifiers and proofs. */
export function Ledger(): JSX.Element {
  return <section className="bg-[var(--bg-secondary)] px-6 py-32 md:py-48"><FadeIn className="mx-auto max-w-6xl"><p className="font-mono text-xs uppercase tracking-[0.15em] text-[var(--accent)]">the ledger</p><div className="mt-5 grid gap-5 md:grid-cols-[1.4fr_0.8fr]"><div className="ledger-frame rounded-2xl p-6 md:p-8"><div className="flex items-center justify-between border-b border-[var(--border-subtle)] pb-5"><span className="font-mono text-xs text-[var(--text-muted)]">private note lifecycle</span><ArrowUpRight size={16} className="text-[var(--accent)]" /></div><div className="mt-8 space-y-5 font-mono text-xs"><div className="flex items-center justify-between"><span className="text-[var(--text-muted)]">note_01</span><span className="text-[var(--text-secondary)]">shielded</span></div><div className="h-px bg-[var(--border-subtle)]" /><div className="flex items-center justify-between"><span className="text-[var(--text-muted)]">nullifier_02</span><span className="text-[var(--accent)]">spent</span></div><div className="h-px bg-[var(--border-subtle)]" /><div className="flex items-center justify-between"><span className="text-[var(--text-muted)]">note_03</span><span className="text-[var(--success)]">minted</span></div></div><p className="mt-10 border-t border-[var(--border-subtle)] pt-5 font-mono text-xs text-[var(--text-muted)]">amount: not disclosed<br />counterparty: not disclosed<br />wallet: not disclosed</p></div><div className="grid gap-5 sm:grid-cols-3 md:grid-cols-1"><InfoCard title="Notes" copy="Encrypted value moves as spendable UTXOs." /><InfoCard title="Nullifiers" copy="Every spend is fresh and cannot be replayed." /><InfoCard title="Selective proof" copy="A lender gets one answer and nothing extra." /></div></div></FadeIn></section>
}

function InfoCard({ title, copy }: { title: string; copy: string }): JSX.Element { return <div className="rounded-2xl border border-[var(--border-subtle)] bg-[var(--bg-surface)] p-6"><span className="font-mono text-xs uppercase tracking-[0.15em] text-[var(--accent)]">{title}</span><p className="mt-5 text-sm leading-[1.6] text-[var(--text-secondary)]">{copy}</p></div> }
