import { Check, LockKeyhole } from 'lucide-react'
import { FadeIn } from '../ui/FadeIn'
import { navigate } from '../../lib/navigation'

/** Show the selective proof surface and invite the next question. */
export function Proof(): JSX.Element {
  return <section id="proof" className="bg-[var(--bg-secondary)] px-6 py-32 md:py-48"><div className="mx-auto grid max-w-6xl gap-16 md:grid-cols-2 md:items-center"><FadeIn><p className="font-mono text-xs uppercase tracking-[0.15em] text-[var(--accent)]">the proof</p><h2 className="mt-5 max-w-md font-serif text-[clamp(2rem,4vw,3.25rem)] leading-[1.08]">Show the record, keep the story private.</h2><p className="mt-6 max-w-md text-base leading-[1.7] text-[var(--text-secondary)]">A new lender asks whether you repaid eleven of eleven loans on time. Tessera returns the answer without returning your amounts, peers or address.</p><button className="mt-8 rounded-full bg-[var(--accent)] px-6 py-3 text-sm font-medium text-[var(--bg-primary)] transition-colors hover:bg-[var(--accent-hover)]" onClick={() => navigate('/app/proof')}>Ask for a proof</button></FadeIn><FadeIn delay={0.15} className="ledger-frame rounded-2xl p-6 md:p-8"><div className="flex items-center gap-3 border-b border-[var(--border-subtle)] pb-5"><LockKeyhole size={16} className="text-[var(--accent)]" /><span className="font-mono text-xs uppercase tracking-[0.15em] text-[var(--text-muted)]">selective proof</span></div><div className="mt-6 space-y-4 font-mono text-sm"><ProofRow label="question" value="repaid 11 of 11 loans on time?" /><ProofRow label="answer" value="true" positive /><ProofRow label="amount" value="not disclosed" /><ProofRow label="peer" value="not disclosed" /><ProofRow label="address" value="not disclosed" /></div><div className="mt-7 flex items-center gap-2 border-t border-[var(--border-subtle)] pt-5 font-mono text-xs text-[var(--success)]"><Check size={14} /> verified statement</div></FadeIn></div></section>
}

function ProofRow({ label, value, positive = false }: { label: string; value: string; positive?: boolean }): JSX.Element { return <div className="grid grid-cols-[5rem_1fr] gap-4"><span className="text-[var(--text-muted)]">{label}</span><span className={positive ? 'text-[var(--success)]' : 'text-[var(--text-secondary)]'}>{value}</span></div> }
