import { Check, LockKeyhole } from 'lucide-react'
import { useProof } from '../../hooks/useProof'
import { SkeletonBlock } from './SkeletonBlock'
import { StatusLine } from './StatusLine'

/** Render the single-question selective credit proof flow. */
export function Proof(): JSX.Element {
  const { proof, generateProof, isSubmitting, status } = useProof()
  const rows = proof ? [{ name: 'question', value: proof.statement }, { name: 'answer', value: proof.answer ? 'true' : 'false' }, ...proof.fields.map((field) => ({ name: field.name, value: field.value ?? 'not disclosed' }))] : [{ name: 'question', value: 'repaid 11 of 11 loans on time?' }, { name: 'answer', value: 'awaiting proof' }, { name: 'amount', value: 'not disclosed' }, { name: 'peer', value: 'not disclosed' }, { name: 'address', value: 'not disclosed' }]
  return <article className="mx-auto max-w-2xl"><StatusLine>step 05 · selective disclosure</StatusLine><h1 className="mt-5 font-serif text-[clamp(2rem,4vw,3.25rem)] leading-[1.08]">Prove you repay.</h1><p className="mt-5 max-w-xl text-base leading-[1.6] text-[var(--text-secondary)]">Ask one question and get one answer. Nothing else is disclosed.</p><div className="ledger-frame mt-12 rounded-2xl p-6 md:p-8"><div className="flex items-center gap-3 border-b border-[var(--border-subtle)] pb-5"><LockKeyhole size={16} className="text-[var(--accent)]" /><span className="font-mono text-xs uppercase tracking-[0.15em] text-[var(--text-muted)]">proof statement</span></div><div className="mt-6 space-y-4 font-mono text-sm">{rows.map((row) => <div className="grid grid-cols-[5rem_1fr] gap-4" key={row.name}><span className="text-[var(--text-muted)]">{row.name}</span><span className={row.name === 'answer' && proof?.answer ? 'text-[var(--success)]' : 'text-[var(--text-secondary)]'}>{row.value}</span></div>)}</div>{proof && <div className="mt-7 flex items-center gap-2 border-t border-[var(--border-subtle)] pt-5 font-mono text-xs text-[var(--success)]"><Check size={14} /> answer verified</div>}</div><button disabled={isSubmitting} className="liquid-glass-strong mt-8 rounded-full px-6 py-3 text-sm font-medium text-[var(--text-primary)] transition-transform hover:scale-[1.02] disabled:cursor-wait disabled:opacity-60" onClick={async () => { try { await generateProof() } catch { return } }}>Generate proof</button><div className="mt-7 space-y-3"><StatusLine tone={proof ? 'success' : 'default'}>{proof?.transactionHash ? `proof: ${proof.transactionHash} verified on mainnet` : status}</StatusLine>{isSubmitting && <SkeletonBlock className="h-5 w-64" />}</div></article>
}
